import Head from 'next/head'
import { LoginTemplate } from '@/shared/templates'

export default function Home() {
  return (
    <>
      <Head>
        <title>Integration test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <LoginTemplate />
      </main>
    </>
  )
}
